name: love photography blog
favicon: null
layout_spectrum: 0.1931345530319959
typography_spectrum: 0.1804853561334312
title: "The blog for the Gold Coast's #1 family portraiture photography business"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9823806234635413
  lightness: 0.008772647939622402
  saturation: 0.31881659058853984
  rhythmicContrast: 0.4692020392976701
purpose: []
